deploy revision - auto tag, based on date

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -17,7 +17,7 @@ workflows:
     - script@1.1.0:
         title: docker infos & images
         inputs:
-        - content: |-
+        - content: |
             #!/bin/bash
             set -e
             set -x
@@ -28,7 +28,7 @@ workflows:
     - script@1.1.0:
         title: docker build
         inputs:
-        - content: |-
+        - content: |
             #!/bin/bash
             set -e
             set -x
@@ -39,16 +39,26 @@ workflows:
     - script@1.1.0:
         title: run platform_report.sh
         inputs:
-        - content: |-
+        - content: |
             #!/bin/bash
             set -e
             set -x
 
             docker run --rm -v "$(pwd)/system_report.sh:/bitrise/src/system_report.sh" -v "/var/run/docker.sock:/var/run/docker.sock" "${DOCKERHUB_IMG_ID}:latest" bash /bitrise/src/system_report.sh
 
+  _generate_image_deploy_tag:
+    steps:
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -ex
+            envman add --key 'DOCKER_IMAGE_DEPLOY_TAG' --value "$(date +%Y_%m_%d-%H_%M)"
+
   deploy:
     before_run:
     - rebuild
+    - _generate_image_deploy_tag
     steps:
     - slack@2.1.0:
         run_if: .IsCI
@@ -57,15 +67,16 @@ workflows:
         - channel: $SLACK_CHANNEL
         - from_username: "$BITRISE_APP_TITLE - OK"
         - from_username_on_error: "$BITRISE_APP_TITLE - ERROR"
-        - message: |-
+        - message: |
             Started:
 
             - Build URL: $BITRISE_BUILD_URL
             - Build Number: $BITRISE_BUILD_NUMBER
+            - Image tag: $DOCKER_IMAGE_DEPLOY_TAG
     - script@1.1.0:
         title: docker login
         inputs:
-        - content: |-
+        - content: |
             #!/bin/bash
             set -e
             echo "=> Docker login..."
@@ -73,7 +84,7 @@ workflows:
     - script@1.1.0:
         title: docker push
         inputs:
-        - content: |-
+        - content: |
             #!/bin/bash
 
             function docker_push_with_retry {
@@ -92,17 +103,18 @@ workflows:
               echo " => Pushing - OK"
             }
 
-            if [ ! -z "${BITRISE_GIT_TAG}" ] ; then
-              echo " => Tagging: ${BITRISE_GIT_TAG} ..."
-              docker tag -f "${DOCKERHUB_IMG_ID}:latest" "${DOCKERHUB_IMG_ID}:${BITRISE_GIT_TAG}"
-              if [ $? -ne 0 ] ; then
-                echo " [!] ERROR: failed to tag the image"
-                exit 1
-              fi
-              docker_push_with_retry "${DOCKERHUB_IMG_ID}:${BITRISE_GIT_TAG}"
-            else
-              docker_push_with_retry "${DOCKERHUB_IMG_ID}:latest"
+            if [ -z "${DOCKER_IMAGE_DEPLOY_TAG}" ] ; then
+              echo " [!] No DOCKER_IMAGE_DEPLOY_TAG specified!"
+              exit 1
             fi
+
+            echo " => Tagging: ${DOCKER_IMAGE_DEPLOY_TAG} ..."
+            docker tag -f "${DOCKERHUB_IMG_ID}:latest" "${DOCKERHUB_IMG_ID}:${DOCKER_IMAGE_DEPLOY_TAG}"
+            if [ $? -ne 0 ] ; then
+              echo " [!] ERROR: failed to tag the image"
+              exit 1
+            fi
+            docker_push_with_retry "${DOCKERHUB_IMG_ID}:${DOCKER_IMAGE_DEPLOY_TAG}"
     - slack@2.1.0:
         run_if: .IsCI
         inputs:
@@ -110,11 +122,12 @@ workflows:
         - channel: $SLACK_CHANNEL
         - from_username: "$BITRISE_APP_TITLE - OK"
         - from_username_on_error: "$BITRISE_APP_TITLE - ERROR"
-        - message: |-
+        - message: |
             Finished:
 
             - Branch: *$BITRISE_GIT_BRANCH*
             - Tag: $BITRISE_GIT_TAG
+            - Image tag: $DOCKER_IMAGE_DEPLOY_TAG
             - Build URL: $BITRISE_BUILD_URL
             - Build Number: $BITRISE_BUILD_NUMBER
             - Build Message: $BITRISE_GIT_MESSAGE
