Quay mirror

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -13,11 +13,61 @@ app:
   - SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
   - SLACK_CHANNEL: $SLACK_CHANNEL
   - CONFIG_do_not_deploy_latest_tag: $CONFIG_do_not_deploy_latest_tag
+
+  - QUAY_IMG_ID: quay.io/bitriseio/bitrise-base
+  - QUAY_LOGIN_USER: $QUAY_LOGIN_USER
+  - QUAY_LOGIN_PASS: $QUAY_LOGIN_PASS
+  - IS_ALPHA: true
 workflows:
   _alpha_envs:
     envs:
     - DOCKERHUB_IMG_ID: $DOCKERHUB_IMG_ID_ALPHA
     - DOCKER_FILE_PATH: $DOCKER_FILE_PATH_ALPHA
+    - IS_ALPHA: true
+
+  _pinned_envs:
+    envs:
+    - DOCKERHUB_IMG_ID: $DOCKERHUB_IMG_ID_PINNED
+    - DOCKER_FILE_PATH: $DOCKER_FILE_PATH_PINNED
+    - IS_ALPHA: false
+
+  _generate_image_deploy_tag:
+    steps:
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -ex
+            envman add --key 'DOCKER_IMAGE_DEPLOY_TAG' --value "v$(date +%Y_%m_%d-%H_%M)-b${BITRISE_BUILD_NUMBER}"
+
+  _rebuild:
+    after_run:
+    - _run_system_report
+    steps:
+    - script@1.1.0:
+        title: docker infos & images
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -ex
+            #
+            docker images
+            df -kh ./
+            docker info
+    - script@1.1.0:
+        title: docker build
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -ex
+            #
+            docker_build_args="--pull --no-cache"
+            if [[ "${IS_CLEAN_BUILD}" == "no" ]] ; then
+              docker_build_args=""
+            fi
+            docker build ${docker_build_args} -t "${DOCKERHUB_IMG_ID}:latest" --file "${DOCKER_FILE_PATH}" .
+            docker images
+
   _deploy:
     before_run:
     - _generate_image_deploy_tag
@@ -31,11 +81,14 @@ workflows:
             set -e
             echo "=> Docker login..."
             docker login -u "${DOCKER_LOGIN_USER}" -p "${DOCKER_LOGIN_PASS}"
+            echo "=> Quay.io login..."
+            docker login -u "${QUAY_LOGIN_USER}" -p "${QUAY_LOGIN_PASS}" quay.io
     - script@1.1.0:
         title: docker push
         inputs:
         - content: |
             #!/bin/bash
+            set -x
 
             function docker_push_with_retry {
               local push_id="$1"
@@ -68,6 +121,54 @@ workflows:
             if [[ "${CONFIG_do_not_deploy_latest_tag}" != "true" ]] ; then
               docker_push_with_retry "${DOCKERHUB_IMG_ID}:latest"
             fi
+    - script@1.1.0:
+        title: quay.io push
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -x
+
+            function quay_push_with_retry {
+              local push_id="$1"
+              echo " => Pushing: ${push_id} ..."
+              docker push "${push_id}"
+              if [ $? -ne 0 ] ; then
+                echo " (!) WARNING: First push attempt failed - retry..."
+                sleep 10
+                docker push "${push_id}"
+                if [ $? -ne 0 ] ; then
+                  echo " [!] ERROR: Second push attempt failed"
+                  exit 1
+                fi
+              fi
+              echo " => Pushing - OK"
+            }
+
+            if [ -z "${DOCKER_IMAGE_DEPLOY_TAG}" ] ; then
+              echo " [!] No DOCKER_IMAGE_DEPLOY_TAG specified!"
+              exit 1
+            fi
+
+            if [[ "${IS_ALPHA}" == "true" ]]; then
+              image_tag="alpha-${DOCKER_IMAGE_DEPLOY_TAG}"
+              latest_image_tag="alpha"
+            else
+              image_tag="${DOCKER_IMAGE_DEPLOY_TAG}"
+              latest_image_tag="latest"
+            fi
+
+            echo " => Tagging: ${image_tag} ..."
+            docker tag "${DOCKERHUB_IMG_ID}:latest" "${QUAY_IMG_ID}:${image_tag}"
+            docker tag "${DOCKERHUB_IMG_ID}:latest" "${QUAY_IMG_ID}:${latest_image_tag}"
+            if [ $? -ne 0 ] ; then
+              echo " [!] ERROR: failed to tag the image"
+              exit 1
+            fi
+
+            quay_push_with_retry "${QUAY_IMG_ID}:${image_tag}"
+            if [[ "${CONFIG_do_not_deploy_latest_tag}" != "true" ]] ; then
+              quay_push_with_retry "${QUAY_IMG_ID}:${latest_image_tag}"
+            fi
     - slack@2.1.0:
         run_if: '{{.IsCI | and .IsBuildFailed}}'
         inputs:
@@ -85,45 +186,7 @@ workflows:
             - Build URL: $BITRISE_BUILD_URL
             - Build Number: $BITRISE_BUILD_NUMBER
             - Build Message: $BITRISE_GIT_MESSAGE
-  _generate_image_deploy_tag:
-    steps:
-    - script:
-        inputs:
-        - content: |
-            #!/bin/bash
-            set -ex
-            envman add --key 'DOCKER_IMAGE_DEPLOY_TAG' --value "v$(date +%Y_%m_%d-%H_%M)-b${BITRISE_BUILD_NUMBER}"
-  _pinned_envs:
-    envs:
-    - DOCKERHUB_IMG_ID: $DOCKERHUB_IMG_ID_PINNED
-    - DOCKER_FILE_PATH: $DOCKER_FILE_PATH_PINNED
-  _rebuild:
-    after_run:
-    - _run_system_report
-    steps:
-    - script@1.1.0:
-        title: docker infos & images
-        inputs:
-        - content: |
-            #!/bin/bash
-            set -ex
-            #
-            docker images
-            df -kh ./
-            docker info
-    - script@1.1.0:
-        title: docker build
-        inputs:
-        - content: |
-            #!/bin/bash
-            set -ex
-            #
-            docker_build_args="--pull --no-cache"
-            if [[ "${IS_CLEAN_BUILD}" == "no" ]] ; then
-              docker_build_args=""
-            fi
-            docker build ${docker_build_args} -t "${DOCKERHUB_IMG_ID}:latest" --file "${DOCKER_FILE_PATH}" .
-            docker images
+
   _run_system_report:
     steps:
     - script@1.1.0:
@@ -139,22 +202,7 @@ workflows:
               -v "$(which bitrise-bridge):/usr/local/bin/bitrise-bridge" \
               -e CI="$CI" \
               "${DOCKERHUB_IMG_ID}:latest" bash /bitrise/src/system_report.sh
-  # _slack_start:
-  #   steps:
-  #   - slack@2.1.0:
-  #       run_if: .IsCI
-  #       inputs:
-  #       - webhook_url: $SLACK_WEBHOOK_URL
-  #       - channel: $SLACK_CHANNEL
-  #       - from_username: $BITRISE_APP_TITLE - OK
-  #       - from_username_on_error: $BITRISE_APP_TITLE - ERROR
-  #       - message: |
-  #           Started:
 
-  #           - Build URL: $BITRISE_BUILD_URL
-  #           - Build Number: $BITRISE_BUILD_NUMBER
-  #           - Image ID: $DOCKERHUB_IMG_ID
-  #           - Image tag: $DOCKER_IMAGE_DEPLOY_TAG
   deploy-alpha:
     before_run:
     - _alpha_envs
